material = 'rubrene2';
%eV = linspace(1239.8/560,1239.8/282,300);
epsilon = MaterialLib(material,1239.8./eV);

d = 50;
MM = MMcalcPW(layerCrystal(material,d,[0,0,0]),1239.8./eV,0,0,0);
A = imag(d*2*pi*(eV./1239.8).*( sqrt(epsilon(1,:)) + sqrt(epsilon(2,:)) ));
A = A.';
A2 = squeeze(log(MM(1,1,:)));
plotter(eV,[A,A2],...
    'title','Calculated spectra for 50 nm Rubrene down c',...
    'ylabel','ln(Transmittance)',...
    'xlabel','eV',...
    'fontsize',16,...
    'legend',{'',{'Absorption','Absorbance'}})

d = 500;
MM = MMcalcPW(layerCrystal(material,d,[0,0,0]),1239.8./eV,0,0,0);
A = imag(d*2*pi*(eV./1239.8).*( sqrt(epsilon(1,:)) + sqrt(epsilon(2,:)) ));
A = A.';
A2 = -squeeze(log(MM(1,1,:)));
plotter(eV,[A,A2],...
    'title','Calculated spectra for 500 nm Rubrene down c',...
    'ylabel','ln(Transmittance)',...
    'xlabel','eV',...
    'fontsize',16,...
    'legend',{'',{'Absorption','Absorbance'}})


MM = MMcalcPW(layerCrystal(material,500,[0,90,0]),1239.8./eV,0,0,0);
A = imag(500*2*pi*(eV./1239.8).*( sqrt(epsilon(1,:)) + sqrt(epsilon(3,:)) ));
A = A.';
A2 = -squeeze(log(MM(1,1,:)));
plotter(eV,[A,A2],...
    'title','Calculated spectra for 500 nm Rubrene down b',...
    'ylabel','ln(Transmittance)',...
    'xlabel','eV',...
    'fontsize',16,...
    'legend',{'',{'Absorption','Absorbance'}})


MM = MMcalcPW(layerCrystal(material,500,[0,90,90]),1239.8./eV,0,0,0);
A = imag(500*2*pi*(eV./1239.8).*( sqrt(epsilon(3,:)) + sqrt(epsilon(2,:)) ));
A = A.';
A2 = -squeeze(log(MM(1,1,:)));
plotter(eV,[A,A2],...
    'title','Calculated spectra for 500 nm Rubrene down a',...
    'ylabel','ln(Transmittance)',...
    'xlabel','eV',...
    'fontsize',16,...
    'legend',{'',{'Absorption','Absorbance'}})


plotter(eV,real(MaterialLib('rubrene',1239.8./eV)),...
    'title','Optical function of orthorhombic rubrene',...
    'xlabel','eV',...
    'ylabel','Re(\epsilon)',...
    'legend',{'Component',{'\epsilon_{x}','\epsilon_{y}','\epsilon_{z}'}},...
    'fontsize',16)

plotter(eV,-imag(MaterialLib('rubrene',1239.8./eV)),...
    'title','Optical function of orthorhombic rubrene',...
    'xlabel','eV',...
    'ylabel','Im(\epsilon)',...
    'legend',{'Component',{'\epsilon_{x}','\epsilon_{y}','\epsilon_{z}'}},...
    'fontsize',16)

mat = diag([a-b,a+b]);
mat = kron(mat,conj(mat));

p = [0.3 0.5 0.6];
q = [0.1 0.2 0.22];
L = SO31([p,q]);
boost = SO31([p./norm(p),0,0,0]);
rotat = SO31([0,0,0,q./norm(q)]);
eig(rotat+boost)
M2 = expm(L)

% x = norm(q);
% y = norm(p);
% L = rotat + boost;
% M = ((eye(4)-L^2)*cos(x) + (eye(4)+L^2)*cosh(y) + (L - L^3)*sin(x) + (L + L^3)*sinh(y))/2
% M2./M

eye(4) + boost^2*(cosh(norm(p)) - 1) + boost*sinh(norm(p))
eye(4) + rotat^2*(1 - cos(norm(q)) ) + rotat*sin(norm(q))

eye(4) +(boost+rotat)^2*(1- cos(norm(q)+1i*norm(p)) )+ (boost + rotat)*sin(norm(q)+1i*norm(p))

eye(4)+(1/2)*( sqrt(norm(p) + 

